In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
# Sample documents
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [3]:
query="keyword-based search"

In [4]:
import re
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    return text


In [5]:
preprocess_documents=[preprocess_text(doc) for doc in documents]

In [6]:
preprocess_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [7]:
print("Preprocessed Documents:")
for doc in preprocess_documents:
    print(doc)

Preprocessed Documents:
this is a list which containig sample documents
keywords are important for keywordbased search
document analysis involves extracting keywords
keywordbased search relies on sparse embeddings


In [8]:
print("Preprocessed Query:")
print(query)

Preprocessed Query:
keyword-based search


In [9]:
preprocessed_query = preprocess_text(query)

In [10]:
preprocessed_query

'keywordbased search'

In [11]:
vector=TfidfVectorizer()

In [12]:
X=vector.fit_transform(preprocess_documents)

In [13]:
X.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [14]:
X.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [15]:
query_embedding=vector.transform([preprocessed_query])

In [16]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [17]:
similarities = cosine_similarity(X, query_embedding)

In [18]:
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [19]:
np.argsort(similarities,axis=0)

array([[0],
       [2],
       [3],
       [1]])

In [20]:
ranked_indices=np.argsort(similarities,axis=0)[::-1].flatten()


In [21]:
ranked_documents = [documents[i] for i in ranked_indices]

In [22]:
#Ranking
ranked_indices=np.argsort(similarities,axis=0)[::-1].flatten()

In [23]:
ranked_indices


array([1, 3, 2, 0])

In [24]:
# Output the ranked documents
for i, doc in enumerate(ranked_documents):
    print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: Document analysis involves extracting keywords.
Rank 4: This is a list which containig sample documents.


In [25]:
query

'keyword-based search'

In [26]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [27]:
#https://huggingface.co/sentence-transformers

In [28]:
document_embeddings = np.array([
    [0.634, 0.234, 0.867, 0.042, 0.249],
    [0.123, 0.456, 0.789, 0.321, 0.654],
    [0.987, 0.654, 0.321, 0.123, 0.456]
])

In [29]:
# Sample search query (represented as a dense vector)
query_embedding = np.array([[0.789, 0.321, 0.654, 0.987, 0.123]])

In [30]:
# Calculate cosine similarity between query and documents
similarities = cosine_similarity(document_embeddings, query_embedding)

In [31]:
similarities

array([[0.73558979],
       [0.67357898],
       [0.71517305]])

In [32]:
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()

In [33]:
ranked_indices

array([0, 2, 1])

In [34]:
# Output the ranked documents
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: Document {idx+1}")

Rank 1: Document 1
Rank 2: Document 3
Rank 3: Document 2


In [40]:
doc_path="/content/countingtheinvisible_pakistan.pdf"

In [41]:
!pip install pypdf

In [42]:
!pip install langchain_community

In [43]:
from langchain_community.document_loaders import PyPDFLoader

In [44]:
loader=PyPDFLoader(doc_path)

In [45]:
docs=loader.load()

In [46]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [47]:
splitter = RecursiveCharacterTextSplitter(chunk_size=200,chunk_overlap=30)

In [48]:
chunks = splitter.split_documents(docs)

In [49]:
chunks

[Document(page_content='Technical Report – Pakistan', metadata={'source': '/content/countingtheinvisible_pakistan.pdf', 'page': 0}),
 Document(page_content='plan-international.org  Counting  the Invisible  – Technical  Report  Pakistan  1  \n \nAcronyms    3 \nGlossary    4 \nAcknowledgement    7 \nSection 1:  Intro duction and rationale    8', metadata={'source': '/content/countingtheinvisible_pakistan.pdf', 'page': 1}),
 Document(page_content='1.1 Introduction  8 \n1.2 Background and rationale  8 \n1.3 Research objectives  9 \n1.4 Methodology  12 \n1.4.1 Research sample  12 \n1.4.2 Characteristics and identities of girls  12', metadata={'source': '/content/countingtheinvisible_pakistan.pdf', 'page': 1}),
 Document(page_content='1.4.3 Field data collection  18 \n1.4.4 Quantitative survey questions  19 \n1.4.5 Qualitative survey quest ions 19 \n1.4.6 Creative and reflective workshops  20 \n1.4.7 Research task teams  20', metadata={'source': '/content/countingtheinvisible_pakistan.pdf',

In [50]:
from langchain.embeddings import HuggingFaceInferenceAPIEmbeddings

In [51]:
HF_TOKEN="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"

In [52]:
embeddings = HuggingFaceInferenceAPIEmbeddings(api_key=HF_TOKEN, model_name="BAAI/bge-base-en-v1.5")

In [53]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.5/559.5 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 91.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 18.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 13.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 35.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 M

In [54]:
from langchain.vectorstores import Chroma

In [56]:
vectorstore=Chroma.from_documents(chunks,embeddings)

In [57]:
vectorstore_retreiver = vectorstore.as_retriever(search_kwargs={"k": 3})

In [58]:
vectorstore_retreiver

VectorStoreRetriever(tags=['Chroma', 'HuggingFaceInferenceAPIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x7b8976b407f0>, search_kwargs={'k': 3})

In [59]:
!pip install rank_bm25

In [60]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever

In [61]:
keyword_retriever = BM25Retriever.from_documents(chunks)

In [62]:
keyword_retriever.k =  3

In [63]:
ensemble_retriever = EnsembleRetriever(retrievers=[vectorstore_retreiver,keyword_retriever],weights=[0.3, 0.7])

# Mixing vector search and keyword search for Hybrid search

## hybrid_score = (1 — alpha) * sparse_score + alpha * dense_score

In [64]:
model_name = "HuggingFaceH4/zephyr-7b-beta"

In [65]:
!pip install bitsandbytes

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 13.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-

In [66]:
!pip install accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.4/309.4 kB 8.5 MB/s eta 0:00:00


In [67]:
import torch
from transformers import ( AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline, )
from langchain import HuggingFacePipeline

In [68]:
# function for loading 4-bit quantized model
def load_quantized_model(model_name: str):
    """
    model_name: Name or path of the model to be loaded.
    return: Loaded quantized model.
    """
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16,
        quantization_config=bnb_config,
    )
    return model

In [69]:
# initializing tokenizer
def initialize_tokenizer(model_name: str):
    """
    model_name: Name or path of the model for tokenizer initialization.
    return: Initialized tokenizer.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_name, return_token_type_ids=False)
    tokenizer.bos_token_id = 1  # Set beginning of sentence token id
    return tokenizer

In [70]:
tokenizer = initialize_tokenizer(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

In [71]:
model = load_quantized_model(model_name)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

`low_cpu_mem_usage` was None, now set to True since model is quantized.


model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [72]:
pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    use_cache=True,
    device_map="auto",
    max_length=2048,
    do_sample=True,
    top_k=5,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id,
)

In [73]:
llm = HuggingFacePipeline(pipeline=pipeline)

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 0.3. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFacePipeline`.
  warn_deprecated(


In [74]:
from langchain.chains import RetrievalQA

In [75]:
normal_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=vectorstore_retreiver
)

In [76]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=ensemble_retriever
)

In [84]:
response1 = normal_chain.invoke("What are the challenges that adolescent girls face in terms of violence and mobility?")

In [85]:
response1

{'query': 'What are the challenges that adolescent girls face in terms of violence and mobility?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\ndiscussing  violence  in focus  groups,  girls talked  of the restrictions  on their mobility  as \nviolence.  Girls reported  not feeling safe in their homes,  in public  places  nor in their\n\nsafeguard  them  from violence :  \n \n [Interviewer:]   What  types  of violence  are girls more  exposed  to? \n[Girls:]    Restriction  on girls’ mobility .\n\ngirls  in public  and private  spaces,  including  the risks  that adolescent  girls  face \ncompared  to boys,  their  perceptions  and experiences  of reporting  violence,  and their\n\nQuestion: What are the challenges that adolescent girls face in terms of violence and mobility?\nHelpful Answer: According to focus groups, girls reported not feeling safe in b

In [86]:
print(response1.get("result"))

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

discussing  violence  in focus  groups,  girls talked  of the restrictions  on their mobility  as 
violence.  Girls reported  not feeling safe in their homes,  in public  places  nor in their

safeguard  them  from violence :  
 
 [Interviewer:]   What  types  of violence  are girls more  exposed  to? 
[Girls:]    Restriction  on girls’ mobility .

girls  in public  and private  spaces,  including  the risks  that adolescent  girls  face 
compared  to boys,  their  perceptions  and experiences  of reporting  violence,  and their

Question: What are the challenges that adolescent girls face in terms of violence and mobility?
Helpful Answer: According to focus groups, girls reported not feeling safe in both their homes and public places. They identified restrictions on their mobility as a form of violence they are more exposed

In [87]:
response2 = hybrid_chain.invoke("What is commmunity leaders?")

In [82]:
response2

{'query': 'What is commmunity leaders?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\n7.8 Experience and perceptions of violence  81 \n7.9 What adolescent boys think of violence against women and girls – who is responsible?  82\n\n7.9 What  adolescent  boys  think  of violence  again st women  and girls  – who is \nresponsible?   \n \nWhile boys acknowledged that girls are exposed to and experience violence in the home and in\n\nsafeguard  them  from violence :  \n \n [Interviewer:]   What  types  of violence  are girls more  exposed  to? \n[Girls:]    Restriction  on girls’ mobility .\n\nbe capable leaders, it is men who are the preferred  leaders  in the community .  \n \n“Women cannot become a leader while men are l eaders.” ( Jats adolescent girl )\n\n7.3 The importance of the community as an enabling environment  78 \n7.4 Women community leaders as r

In [83]:
print(response2.get("result"))

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

7.8 Experience and perceptions of violence  81 
7.9 What adolescent boys think of violence against women and girls – who is responsible?  82

7.9 What  adolescent  boys  think  of violence  again st women  and girls  – who is 
responsible?   
 
While boys acknowledged that girls are exposed to and experience violence in the home and in

safeguard  them  from violence :  
 
 [Interviewer:]   What  types  of violence  are girls more  exposed  to? 
[Girls:]    Restriction  on girls’ mobility .

be capable leaders, it is men who are the preferred  leaders  in the community .  
 
“Women cannot become a leader while men are l eaders.” ( Jats adolescent girl )

7.3 The importance of the community as an enabling environment  78 
7.4 Women community leaders as role models  78 
7.5 Gender norms  78 
7.6 Education and pathways to empow